config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/users/manage" => "users#manage"

  get "/" => "home#index", as: :home

  get "/schedules/summary" => "schedules:summary"

  resources :schedules
  resources :users
  resources :taskdetails

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :first_name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :schedules, foreign_key: :patient_id
  has_many :schedules, foreign_key: :doctor_id

  def full_name
    first_name + " " + last_name
  end

  def patient_name
    User.find(patient_id).full_name
  end

  def self.patients
    where(user_role: "patient")
  end

  def self.doctors
    where(user_role: "doctor")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_id
  @show_user = "both"

  def index
    @show_user = session[:show_user]
    @show_user = (@show_user == nil || @show_user.empty?) ? "both" : @show_user
    show()
  end

  def manage
    ensure_user_logged_id()
    if current_user.user_role != "admin"
      render session_path
    end
    find_users_by_role()
    render "/users/manage"
  end

  def find_users_by_role
    @show_user = params[:show_user] == nil ? session[:show_user] : params[:show_user]
    @show_user = (@show_user == nil || @show_user.empty?) ? "both" : @show_user
    session[:show_user] = @show_user
    if @show_user != "both"
      @users = User.where(user_role: @show_user).order(:id)
    else
      @users = User.all.order(:id)
    end
  end

  def find_active_user_by_status
    @active_user = params[:active_user] == nil ? session[:active_user] : params[:active_user]
    @active_user = (@active_user == nil || @active_user.empty?) ? "both" : @active_user
    session[:active_user] = @active_user
    if @active_user != "both"
      @users = User.where(active_user: @active_user)
    else
      @users = User.all
    end
  end

  def show
    find_active_user_by_status()
    if current_user
      if current_user.user_role == "admin"
        render "admin_dashboard"
      elsif current_user.user_role == "doctor"
        redirect_to schedules_path
      end
    else
      render "new"
    end
  end

  def new
    if current_user && current_user.user_role == "admin"
      ensure_user_logged_id()
    end
    render "new"
  end

  def create
    @user_role = "patient"

    if current_user && current_user.user_role == "admin"
      @user_role = "doctor"
    end
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: (params[:password]),
      user_role: @user_role,
      active_user: true,
    )
    if !new_user.save
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to new_user_path
    else
      if @user_role == "doctor"
        flash[:info] = "Successfully doctor added!"
        manage()
      else
        flash[:info] = "Congrats, Successfully Registered!"
        session[:current_user_id] = new_user.id
        redirect_to schedules_path
      end
    end
  end

  def update
    user_id = params[:id]
    active_user = params[:active_user] ? params[:active_user] : false
    user = User.find(user_id)
    user.active_user = active_user
    user.save!
    manage()
  end

  def edit
    @user_id = params[:id].to_i
    @first_name = params[:first_name]
    @last_name = params[:last_name]
    @email = params[:email]
    @user_role = params[:user_role]

    @button = params[:button]
    if @button == "save"
      @user = User.find(@user_id)
      @user.first_name = @first_name
      @user.last_name = @last_name
      @user.email = @email
      @user.user_role = @user_role == nil || @user_role.empty? ? @user.user_role : @user_role
      @user.save!
    end
    manage()
  end

  def destroy
    id = params[:id]
    user = User.find(id)
    user.destroy
    flash[:info] = "User deleted Successfully!"
    manage()
  end
end

app/views/users/admin_dashboard.html.erb
<div class="AdminDashboardPage">
    <div class="DashboardPage-header">
        <p class="DashboardPage-title">Admin Dashboard</p>
        <div class="DashboardPage-links">
            <%= link_to  image_tag("add.jpg", class: "Schedule-img-task", alt: "Add New Doctor") , new_user_path , title: "Add New Doctor" %>
            <%= link_to  image_tag("users.png", class: "Schedule-img-task", alt: "Manage User") , "/users/manage", title: "Manage User" %>
        </div>
    </div>
    <hr/>
    <section class="DashboardPage-schedules-selection">
        <% @active_user = session[:active_user] %>
        <% @active_user = (@active_user == nil || @active_user.empty?) ? "both" : @active_user %>
        <%= form_with(url: "/users/show", method: "get") do %>
            Show <%= radio_button_tag :active_user, "true", @active_user == "true" ? true : false, onclick: "this.form.submit()" %> Only Active Users
            <%= radio_button_tag :active_user, "false", @active_user == "false" ? true : false, onclick: "this.form.submit()" %> Only Inactive Users
            <%= radio_button_tag :active_user, "both", @active_user == "both" ? true : false, onclick: "this.form.submit()" %> All Users
        <% end %>
    </section>
    <section class="DashboardPage-schedules">
        <div class="DashboardPage-schedule-list">
            <div class="Schedule-block">
                <%= pie_chart @users.group(:user_role).count, title: "No of Users" %>
            </div>
            <div class="Schedule-block">
                <%= column_chart @users.joins("INNER JOIN schedules ON schedules.patient_id = users.id INNER JOIN taskdetails ON taskdetails.schedule_id = schedules.id").group(:first_name).group_by_day(:task_date, format: "%d-%m").count, title: "Patient's Scheduled Tasks Moniter", dataset: { borderWidth: 1 }, empty: "No data", loading: "Loading...", zeros: true, precision: 2, xtitle: "Date", ytitle: "Frequency/User/Day", label: "Value", stacked: false %>
            </div>
        </div>
    </section>
</div>

app/views/users/manage.html.erb
<div class="AdminDashboardPage">
    <div class="DashboardPage-header">
        <p class="DashboardPage-title">Manage Users</p>
        <div class="DashboardPage-links">
            <%= link_to image_tag("add.jpg", class: "Schedule-img-task", alt: "History"), new_user_path, title: "Add New Doctor" %>
            <%= link_to image_tag("dashboard.png", class: "Schedule-img-header", alt: "Dashboard"), users_path, title: "Dashboard" %>
        </div>
    </div>
    <hr/>
    <section class="DashboardPage-schedules-selection">
        <% @show_user = session[:show_user] %>
        <% @show_user = (@show_user == nil || @show_user.empty?) ? "both" : @show_user %>
        <%= form_with(url: "/users/manage", method: "get") do %>
            Show <%= radio_button_tag :show_user, "doctor", @show_user == "doctor" ? true : false, onclick: "this.form.submit()" %> Only doctors
            <%= radio_button_tag :show_user, "patient", @show_user == "patient" ? true : false, onclick: "this.form.submit()" %> Only patients
            <%= radio_button_tag :show_user, "both", @show_user == "both" ? true : false, onclick: "this.form.submit()" %> All users
        <% end %>
    </section>
    <section class="AdminDashboardPage-users">
        <table class="AdminPage-table">
        <tr><th>Active User</th><th>User id</th><th>First Name</th><th>Last Name</th><th>Email ID</th><th>User Role</th><th></th><th></th></tr>
            <% @users.each do |user| %>
             <tr>
                    <td class="Table-cell-center"> 
                        <%= form_with(url: "/users/#{user.id}", method: "put") do %>
                            <%= check_box_tag :active_user, nil, user.active_user, class: "Schedule-checkbox", onclick: "this.form.submit()" %>
                        <% end %>     
                    </td>
                <%= form_with(url: "/users/#{user.id}/edit", method: "get") do %>
                        <td class="Table-cell-center">
                            <%= user.id %>
                        </td>
                        <td>
                            <% if @user_id == user.id && @button == "edit" %>
                                <%= text_field_tag "first_name", user.first_name, class: "AdminDashBoard-edit-textbox" %>
                            <% else %>
                                <%= user.first_name %>
                            <% end %>
                        </td>
                        <td>
                            <% if @user_id == user.id && @button == "edit" %>
                                <%= text_field_tag "last_name", user.last_name, class: "AdminDashBoard-edit-textbox" %>
                            <% else %>
                                <%= user.last_name %>
                            <% end %>
                        </td>
                        <td>
                            <% if @user_id == user.id && @button == "edit" %>
                                <%= text_field_tag "email", user.email %>
                            <% else %>
                                <%= user.email %>
                            <% end %>
                        </td>
                        <td class="Table-cell-center">
                            <% if user.user_role == "admin" %>
                                <%= user.user_role %>
                            <% elsif @user_id == user.id && @button == "edit" %>
                                <%= select_tag "user_role", options_for_select(["doctor", "patient"], user.user_role) %>
                            <% else %>
                                <%= user.user_role %>
                            <% end %>
                        </td>
                        <td class="Table-cell-center">
                        <div class="Schedule-button">
                            <% if @user_id == user.id && @button == "edit" %>
                                <%= hidden_field_tag("button", "save") %>
                                <%= image_submit_tag("save.jpg", class: "Schedule-img-save") %>
                            <% else %>
                                <%= hidden_field_tag("button", "edit") %>
                                <%= image_submit_tag("edit4.ico", class: "Schedule-img") %>
                            <% end %>    
                        </div>
                        </td>
                <% end %>
                        <td class="Table-cell-center">
                        <div class="Schedule-button">
                            <%= link_to image_tag("delete.svg", class: "Schedule-img", alt: "Delete"), "/users/#{user.id}", title: "Delete", method: :delete, data: { confirm: "Are you sure you want to delete this user?" }  %>
                        </div>
                        </td>
                </tr>
            <% end %>
        </table>
    </section>
</div>

app/views/users/new.html.erb
<section class="UsersNew">
    <div class="DashboardPage-header">
        <% if @current_user %>
            <p class="DashboardPage-title">Add new Doctor user!</p>
            <div class="DashboardPage-links">
                <%= link_to  image_tag("users.png", class: "Schedule-img-task", alt: "Manage User") , "/users/manage", title: "Manage Users" %>
                <%= link_to  image_tag("dashboard.png", class: "Schedule-img-header", alt: "Dashboard") , users_path , title: "Dashboard" %>
            </div>
        <% else %>
            <p class="DashboardPage-title">Welcome new user!</p>
        <% end %>
    </div>    
    <%= form_with url: users_path do |form| %>
        <div class="Form-section">
            <p class: "FormInput-label">First Name: </p>
            <%= form.text_field :first_name, class: "Form-input" %>
        </div>
        <div class="Form-section">
            <p class: "FormInput-label">Last Name: </p>
            <%= form.text_field :last_name, class: "Form-input" %>
        </div>
        <div class="Form-section">    
            <p class: "FormInput-label">E-mail: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
            <%= form.email_field :email, class: "Form-input" %>
        </div>
        <div class="Form-section">    
            <p class: "FormInput-label">Password: &nbsp;&nbsp;</p>
            <%= form.password_field :password, class: "Form-input" %>
        </div>
        <div class="Form-section">    
            <%= form.submit "Sign Up", class: "Form-submit" %>
        </div>
    <% end %>
</section>