config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/users/manage" => "users#manage"

  get "/" => "home#index", as: :home

  get "/schedules/summary" => "schedules:summary"

  resources :schedules
  resources :users
  resources :taskdetails

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :patient_id, presence: true
  validates :doctor_id, presence: true
  validates :schedule_slot, presence: true
  validates :duration, presence: true

  belongs_to :patient, class_name: "User"
  belongs_to :doctor, class_name: "User"

  has_many :taskdetails, foreign_key: :schedule_id

  def index
    @schedules = current_user.schedules.order(complete_date: :DESC)
    render "index"
  end

  def patient_name
    User.find(patient_id).full_name
  end

  def doctor_name
    User.find(doctor_id).full_name
  end

  def self.of_user(user)
    if user.user_role == "doctor"
      all.where(doctor_id: user.id)
    else
      all.where(patient_id: user.id)
    end
  end

  def patient_performance()
    no_of_days = (self.complete_date - self.assign_date + 1).to_i
    schedule_slot = self.schedule_slot
    no_of_slots = (schedule_slot.delete '[]""').split().count
    no_of_tasks = no_of_days * no_of_slots
    no_of_completed_task = Taskdetail.where(schedule_id: self.id).count
    no_of_days_till_date = (Date.today() - self.assign_date + 1).to_i
    no_of_expected_task = no_of_days_till_date * no_of_slots
    performance = no_of_completed_task.to_f / no_of_expected_task
    return performance, no_of_completed_task, no_of_expected_task
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :ensure_user_logged_id

  def index
    find_users_shedules()
    check_active_schedules()
    if current_user == nil
      redirect_to home_path
    end
    show()
  end

  def show
    find_users_shedules()
    check_active_schedules()
    @schedules = @schedules.order(:id)

    if @user_role == "doctor"
      render "doctor_dashboard"
    else
      render "patient_dashboard"
    end
  end

  def edit
    find_users_shedules()
    @schedule_id = params[:id].to_i
    @field = params[:field]
    @button = params[:button]
    @user_role = current_user.user_role

    if @button == "save"
      @schedule = @schedules.find(@schedule_id)
      if @field == "duration"
        @schedule.duration = params[:duration]
      elsif @field == "assign_date"
        @schedule.assign_date = params[:assign_date]
      elsif @field == "complete_date"
        @schedule.complete_date = params[:complete_date]
      elsif @field == "schedule_slot" && params[:schedule_slot]
        @schedule.schedule_slot = params[:schedule_slot]
      end
      @schedule.save!
    end
    show()
  end

  def create
    patient_id = params[:patient_id]
    doctor_id = current_user.id
    schedule_slot = params[:schedule_slot]
    duration = params[:duration]
    assign_date = params[:assign_date]
    complete_date = params[:complete_date]
    active_schedule = true
    new_schedule = Schedule.new(
      patient_id: patient_id,
      doctor_id: doctor_id,
      schedule_slot: schedule_slot,
      duration: duration,
      assign_date: assign_date,
      complete_date: complete_date,
      active_schedule: true,
    )
    if !new_schedule.save
      flash[:error] = new_schedule.errors.full_messages.join(", ")
    else
      flash[:info] = "Schedule Added Successfully!"
    end
    redirect_to schedules_path
  end

  def update
    schedule_id = params[:id]
    active_schedule = params[:active_schedule] ? params[:active_schedule] : false
    schedule = Schedule.of_user(current_user).find(schedule_id)
    schedule.active_schedule = active_schedule
    schedule.save!
    redirect_to schedules_path
  end

  def destroy
    schedule_id = params[:id]
    schedule = Schedule.of_user(current_user).find(schedule_id)
    schedule.destroy
    flash[:info] = "Schedule deleted Successfully!"
    redirect_to schedules_path
  end

  def summary
    find_users_shedules()
    check_active_schedules()
    render "summary"
  end

  def find_users_shedules
    if current_user.user_role == "patient"
      @user_role = "patient"
      @schedules = Schedule.where(patient_id: current_user.id)
    elsif current_user.user_role == "doctor"
      @user_role = "doctor"
      @schedules = Schedule.where(doctor_id: current_user.id)
    end
  end

  def check_active_schedules
    @active_schedule = params[:active_schedule] == nil ? session[:active_schedule] : params[:active_schedule]
    @active_schedule = (@active_schedule == nil || @active_schedule.empty?) ? "true" : @active_schedule
    session[:active_schedule] = @active_schedule
    if @active_schedule != "both"
      @schedules = @schedules.where(active_schedule: @active_schedule)
    end
  end
end

app/views/schedules/doctor_dashboard.html.erb
<div class="DashboardPage">
    <div class="DashboardPage-header">
        <p class="DashboardPage-title">Doctor Dashboard</p>
        <div class="DashboardPage-links">
            <%= link_to image_tag("add.jpg", class: "Schedule-img-task", alt: "History"), new_schedule_path %>
            <%= link_to image_tag("summary.png", class: "Schedule-img-task", alt: "Summary"), "/schedules/summary", title: "Summary Report" %>
        </div>
    </div>
    <hr/>
    <section class="DashboardPage-schedules-selection">
        <% @active_schedule = session[:active_schedule] %>
        <% @active_schedule = (@active_schedule == nil || @active_schedule.empty?) ? "true" : @active_schedule %>
        <%= form_with(url: "/schedules/show", method: "get") do %>
            Show <%= radio_button_tag :active_schedule, "true", @active_schedule == "true" ? true : false, onclick: "this.form.submit()" %> Only Active schedules
            <%= radio_button_tag :active_schedule, "false", @active_schedule == "false" ? true : false, onclick: "this.form.submit()" %> Only Inactive schedules
            <%= radio_button_tag :active_schedule, "both", @active_schedule == "both" ? true : false, onclick: "this.form.submit()" %> All Schedules
        <% end %>
    </section>
    <section class="DashboardPage-schedules">
        <div class="DashboardPage-schedule-list">
            <% @schedules.each do |schedule| %>
                <div class="Schedules-li">
                    <div class="Schedule-block">
                        <div class="Schedule-block-firstline">
                        <%= form_with(url: "/schedules/#{schedule.id}", method: "put") do %>
                            <%= check_box_tag :active_schedule, nil, schedule.active_schedule, class: "Schedule-checkbox", onclick: "this.form.submit()" %>
                            Current schedule active or not?
                        <% end %>
                        </div>
                        <div class='Schedule-Text'>
                            <p>Patient Name: </p>
                            <p class="Schedule-Text-value"><%= schedule.patient_name %></p>
                        </div>
                        <div class='Schedule-Text'>
                            <p>Schedule slots: </p>
                            <p class="Schedule-Text-value">
                                <% if @field == "schedule_slot" && @schedule_id == schedule.id && @button == "edit" %>
                                    <%= form_with(url: "/schedules/#{schedule.id}/edit", method: "get") do %>
                                        <%= check_box_tag "schedule_slot[]", "Morning", checked = schedule.schedule_slot.include?("Morning") %> Morning
                                        <%= check_box_tag "schedule_slot[]", "Evening", checked = schedule.schedule_slot.include?("Evening") %> Evening
                                        <%= hidden_field_tag("field", "schedule_slot") %>
                                        <%= hidden_field_tag("button", "save") %>
                                        <%= image_submit_tag("save.jpg", class: "Schedule-img-save") %>
                                    <% end %>
                                <% else %>
                                    <%= schedule.schedule_slot.delete('"[]') %> 
                                    <a href="javascript:void(0)" title="Edit">
                                        <%= form_with(url: "/schedules/#{schedule.id}/edit", method: "get") do %>
                                            <%= hidden_field_tag("field", "schedule_slot") %>
                                            <%= hidden_field_tag("button", "edit") %>
                                            <%= image_submit_tag("edit4.ico", class: "Schedule-img") %>
                                        <% end %>
                                    </a>
                                <% end %>
                            </p>
                        </div>
                        <div class='Schedule-Text'>
                            <p class="Schedule-title" >Brushing Duration: </p>
                            <p class="Schedule-Text-value">
                            <% if @field == "duration" && @schedule_id == schedule.id && @button == "edit" %>
                                <%= form_with(url: "/schedules/#{schedule.id}/edit", method: "get") do %>
                                    <%= number_field_tag "duration", schedule.duration, in: 1..300, class: "Schedule-duration" %>
                                    seconds
                                    <%= hidden_field_tag("field", "duration") %>
                                    <%= hidden_field_tag("button", "save") %>
                                    <%= image_submit_tag("save.jpg", class: "Schedule-img-save") %>
                                <% end %>
                            <% else %>
                                <%= schedule.duration %> seconds
                                <a href="javascript:void(0)" title="Edit">
                                    <%= form_with(url: "/schedules/#{schedule.id}/edit", method: "get") do %>
                                        <%= hidden_field_tag("field", "duration") %>
                                        <%= hidden_field_tag("button", "edit") %>
                                        <%= image_submit_tag("edit4.ico", class: "Schedule-img") %>
                                    <% end %>
                                </a>
                            <% end %>
                            </p>
                        </div>
                        <div class="Schedule-Text">
                            <p class="Schedule-title">Starting Date: </p>
                            <p class="Schedule-Text-value">
                            <% if @field == "assign_date" && @schedule_id == schedule.id && @button == "edit" %>
                                <%= form_with(url: "/schedules/#{schedule.id}/edit", method: "get") do %>
                                    <%= date_field_tag :assign_date, schedule.assign_date, class: "NewSchedulePage-startdate" %>
                                    <%= hidden_field_tag("button", "save") %>
                                    <%= hidden_field_tag("field", "assign_date") %>
                                    <%= image_submit_tag("save.jpg", class: "Schedule-img-save") %>
                                <% end %>
                            <% else %>
                                <%= schedule.assign_date.to_s(:short) %>
                                <a href="javascript:void(0)" title="Edit">
                                <%= form_with(url: "/schedules/#{schedule.id}/edit", method: "get") do %>
                                    <%= hidden_field_tag("field", "assign_date") %>
                                    <%= hidden_field_tag("button", "edit") %>
                                    <%= image_submit_tag("edit4.ico", class: "Schedule-img") %>
                                <% end %>
                                </a>
                            <% end %>
                            </p>
                        </div>
                        <div class="Schedule-Text">
                            <p  class="Schedule-title">Completion Date: </p>
                            <p class="Schedule-Text-value">
                            <% if @field == "complete_date" && @schedule_id == schedule.id && @button == "edit" %>
                                <%= form_with(url: "/schedules/#{schedule.id}/edit", method: "get") do %>
                                    <%= date_field_tag :complete_date, schedule.complete_date, class: "NewSchedulePage-startdate" %>
                                    <%= hidden_field_tag("button", "save") %>
                                    <%= hidden_field_tag("field", "complete_date") %>
                                    <%= image_submit_tag("save.jpg", class: "Schedule-img-save") %>
                                <% end %>
                            <% else %>
                                <%= schedule.complete_date.to_s(:short) %>
                                <a href="javascript:void(0)" title="Edit">
                                <%= form_with(url: "/schedules/#{schedule.id}/edit", method: "get") do %>
                                    <%= hidden_field_tag("field", "complete_date") %>
                                    <%= hidden_field_tag("button", "edit") %>
                                    <%= image_submit_tag("edit4.ico", class: "Schedule-img") %>
                                <% end %>
                                </a>
                            <% end %>
                            </p>
                        </div>
                        <div class="Schedule-Text">
                            <% performance, no_of_completed_task, no_of_expected_task = schedule.patient_performance() %>
                            <p  class="Schedule-title">Performace: </p>
                            <p class="Schedule-Text-value"><%= no_of_completed_task.to_s %> / <%= no_of_expected_task.to_s %> </p>
                        </div>
                        <div class="Schedule-button">
                            <div class="Schedule-block-bar">
                                <div class="Schedule-block-bar-color" style="min-width:<%= performance * 93.6 %>%;background-color: rgb(<%= (255 * (1 - performance)).to_i %>, <%= (255 * (performance)).to_i %>, 0);">
                                <%= (performance * 100).round(2) %> %
                                </div>
                            </div>
                            <%= link_to image_tag("history.png", class: "Schedule-img-task", alt: "History"), "/taskdetails/#{schedule.id}", title: "History" %>
                            <%= link_to image_tag("delete.svg", class: "Schedule-img-delete", alt: "Delete"), "/schedules/#{schedule.id}", title: "Delete", method: :delete, data: { confirm: "Are you sure you want to delete this user?" }  %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </section>
</div>

app/views/schedules/new.html.erb
<section class="NewSchedule">
    <div class="DashboardPage-header">
        <p class="DashboardPage-title">New Schedule</p>
        <%= link_to image_tag("dashboard.png", class: "Schedule-img-header", alt: "Dashboard"), schedules_path, title: "Dashboard" %>    
    </div>
    <hr/>
    <%= form_with url: schedules_path, method: "post" do |form| %>
        <div class="NewSchedule-Form-section">
            <p><%= form.label :patient_id, "Patient Name:" %></p>
            <%= select_tag(:patient_id, options_from_collection_for_select(User.patients, :id, :full_name), class: "NewSchedulePage-dropdown") %>
        </div>
        <div class="NewSchedule-Form-section">
            <p><%= form.label :schedule_slot, "Schedule slots:" %></p>
            <%= check_box_tag "schedule_slot[]", "Morning", false, class: "NewSchedulePage-checkbox" %>Morning
            <%= check_box_tag "schedule_slot[]", "Evening", false, class: "NewSchedulePage-checkbox" %>Evening
        </div>
        <div class="NewSchedule-Form-section">    
            <p><%= form.label :duration, "Duration:" %></p>
            <%= form.number_field :duration, in: 1..300, value: 60, class: "NewSchedulePage-duration" %> seconds
        </div>
        <div class="NewSchedule-Form-section">    
            <p><%= form.label :assign_date, "Start Date:" %></p>
            <%= date_field_tag :assign_date, Date.today(), class: "NewSchedulePage-startdate" %>
        </div>
        <div class="NewSchedule-Form-section">    
            <p><%= form.label :complete_date, "End Date:" %></p>
            <%= date_field_tag :complete_date, Date.today() + 7, class: "NewSchedulePage-enddate" %>
        </div>
        <div class="NewSchedule-Form-section">    
            <%= form.submit "Add Schedule", class: "Form-submit" %>
        </div>
    <% end %>
</section>

app/views/schedules/patient_dashboard.html.erb
<div class="DashboardPage">
    <div class="DashboardPage-header">
        <p class="DashboardPage-title">Patient Dashboard</p>
    </div>
    <hr/>
    <section class="DashboardPage-schedules-selection">
        <% @active_schedule = session[:active_schedule] %>
        <% @active_schedule = (@active_schedule == nil || @active_schedule.empty?) ? "true" : @active_schedule %>
        <%= form_with(url: "/schedules/show", method: "get") do %>
            Show <%= radio_button_tag :active_schedule, "true", @active_schedule == "true" ? true : false, onclick: "this.form.submit()" %> Only Active schedules
            <%= radio_button_tag :active_schedule, "false", @active_schedule == "false" ? true : false, onclick: "this.form.submit()" %> Only Inactive schedules
            <%= radio_button_tag :active_schedule, "both", @active_schedule == "both" ? true : false, onclick: "this.form.submit()" %> All Schedules
        <% end %>
    </section>
    <section class="DashboardPage-schedules">
        <div class="DashboardPage-schedule-list">
            
            <% if @schedules == nil || @schedules.to_a.count == 0%>
                <div>
                    No Schedule Found! Contact to your doctor!
                </div>
            <% else %>
                <% @schedules.each do |schedule| %>
                    <div class="Schedules-li">
                        <div class="Schedule-block">
                            <%= form_with(url: "/schedules/#{schedule.id}", method: "put") do %>
                                <%= check_box_tag :active_schedule, nil, schedule.active_schedule, class: "Schedule-checkbox", onclick: "this.form.submit()" %>
                                Current Status of Schedule, Active or not?
                            <% end %>
                            <div class='Schedule-Text'><p>Doctor Name: </p><p class="Schedule-Text-value"><%= schedule.doctor_name %></p></div>
                            <div class='Schedule-Text'>
                            <p>Brushing Schedule slots: </p>
                            <p class="Schedule-Text-value">
                                <%= schedule.schedule_slot.delete('"[]') %> 
                            </p>
                                
                            </div>
                            <div class='Schedule-Text'>
                            <p class="Schedule-title" >Brushing Duration: </p>
                            <p class="Schedule-Text-value">
                                    <%= schedule.duration %> seconds
                            </p>
                            </div>
                            <div class="Schedule-Text"><p class="Schedule-title">Starting Date: </p>
                            <p class="Schedule-Text-value">
                                    <%= schedule.assign_date.to_s(:short) %>
                            </p>
                            </div>
                            <div class="Schedule-Text"><p  class="Schedule-title">Completion Date: </p>
                            <p class="Schedule-Text-value">
                                    <%= schedule.complete_date.to_s(:short) %>
                            </p>
                            </div>
                            <div class="Schedule-Text">
                                <% performance, no_of_completed_task, no_of_expected_task = schedule.patient_performance() %>
                                <p  class="Schedule-title">Performace: </p>
                                <p class="Schedule-Text-value"><%= no_of_completed_task.to_s %> / <%= no_of_expected_task.to_s %> </p>
                            </div>
                            <div class="Schedule-button">
                                <div class="Schedule-block-bar">
                                    <div class="Schedule-block-bar-color" style="min-width:<%= performance * 93.6 %>%;background-color: rgb(<%= (255 * (1 - performance)).to_i %>, <%= (255 * (performance)).to_i %>, 0);">
                                    <%= (performance * 100).round(2) %> %
                                    </div>
                                </div>
                                <%= link_to image_tag("history.png", class: "Schedule-img-task", alt: "History"), "/taskdetails/#{schedule.id}", title: "History" %>
                            </div>
                            <div class="Schedule-task-block">
                            <%= form_with(url: "/taskdetails", method: "post") do %>
                                <div class="Schedule-task">
                                    <% if schedule.schedule_slot.include?("Morning") %>
                                        <%= radio_button_tag "schedule_slot", "Morning", checked = schedule.schedule_slot.include?("Morning") %> Morning
                                    <% end %>
                                    <% if schedule.schedule_slot.include?("Evening") %>
                                        <%= radio_button_tag "schedule_slot", "Evening", checked = schedule.schedule_slot.include?("Evening") %> Evening
                                    <% end %>         
                                    <a title="Complete" >
                                        <%= hidden_field_tag("schedule_id", schedule.id) %>
                                        <%= hidden_field_tag("duration", schedule.duration) %>
                                        <%= image_submit_tag("task.png", class: "Schedule-img-task", disabled: !schedule.active_schedule) %>
                                    </a>
                                </div>
                            <% end %>
                            </div>
                            
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
    </section>
</div>

app/views/schedules/summary.html.erb
<div class="DashboardPage">
    <div class="DashboardPage-header">
        <p class="DashboardPage-title">Summary of assigned brushing schedule</p>
        <%= link_to image_tag("dashboard.png", class: "Schedule-img-header", alt: "Dashboard"), schedules_path, title: "Dashboard" %>
    </div>
    <hr/>
    <section class="DashboardPage-schedules-selection">
        <% @active_schedule = session[:active_schedule] %>
        <% @active_schedule = (@active_schedule == nil || @active_schedule.empty?) ? "true" : @active_schedule %>
        <%= form_with(url: "/schedules/summary", method: "get") do %>
            Show <%= radio_button_tag :active_schedule, "true", @active_schedule == "true" ? true : false, onclick: "this.form.submit()" %> Only Active schedules
            <%= radio_button_tag :active_schedule, "false", @active_schedule == "false" ? true : false, onclick: "this.form.submit()" %> Only Inactive schedules
            <%= radio_button_tag :active_schedule, "both", @active_schedule == "both" ? true : false, onclick: "this.form.submit()" %> All Schedules
        <% end %>
    </section>
    <section>
        <%= column_chart @schedules.where(doctor_id: @current_user.id).joins("INNER JOIN users ON schedules.patient_id = users.id INNER JOIN taskdetails ON taskdetails.schedule_id = schedules.id").group(:first_name).group_by_day_of_week(:task_date, format: "%d-%m").count, title: "Patient's Scheduled Tasks Moniter", dataset: { borderWidth: 3 }, empty: "No data", loading: "Loading...", zeros: true, precision: 2, xtitle: "Time", ytitle: "Frequency/User", label: "Value", stacked: false, xmin: "2021-09-29", xmax: "2022-01-01" %>
    </section>
</div>