config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/users/manage" => "users#manage"

  get "/" => "home#index", as: :home

  get "/schedules/summary" => "schedules:summary"

  resources :schedules
  resources :users
  resources :taskdetails

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToothBrush</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
    <%= favicon_link_tag "favicon.ico" %>
  </head>

  <body>
    <h1 class="Header-title">Smart Tooth Brush Management</h1>
    <div class="Header-menu">
        <% if flash[:error] %>
            <p class="Flash-error"><%= flash[:error] %><p/>
        <% elsif flash[:info] %>
            <p class="Flash-info"><%= flash[:info] %><p/>
        <% end %> 
            
        <% if @current_user %>
            <p class="Userheader">
              Welcome, <%= @current_user.full_name %>
              &nbsp;&nbsp;&nbsp;&nbsp;
              <%= link_to "Sign-out", destroy_session_path, method: "delete" %>
            </p>
        <% else %>
            <p class="Userheader">
              <%= link_to "Sign-in", sessions_path, method: "get", class: "Userheader-link" %>
              &nbsp;&nbsp;&nbsp;&nbsp;
              <%= link_to "Sign-up", new_user_path, method: "get", class: "Userheader-link" %>
            </p>
        <% end %>
    </div>
    <%= yield %>
  </body>
</html>